apiVersion: apps/v1
kind: Deployment
metadata:
  name: react
  labels:
    app: swiggy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: react
  template:
    metadata:
      labels:
        app: react
    spec:
      containers:
        - name: react
          image: sampathakkina/swiggy
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: swiggy
spec:
  type: NodePort
  selector:
    app: react
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 32000

